name: Deploy

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node version"
        required: true
        type: string
      package-version:
        description: "Package version"
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  deploy:
    name: Deploy to NPM
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: Production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-${{inputs.package-version}}
          path: dist

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version: ${{ inputs.node-version }}
          registry-url: "https://registry.npmjs.org"

      - name: Publish to NPM
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
